[build]
  command = "npm run build"
  publish = "dist"

[template.environment]
  VUE_APP_API_KEY = "AIzaSyC4swNttXJRsjUqv07n_o0-By0U2BBmjg8"
  VUE_APP_FIREBASE_API_KEY = "AIzaSyDtYJXSR2ANljtlXlmYJ1PObZaPWDunWvI"
  VUE_APP_FIREBASE_AUTH_DOMAIN = "poetic-torch-310010.firebaseapp.com"
  VUE_APP_FIREBASE_DATABASE_URL = "https://poetic-torch-310010-default-rtdb.firebaseio.com"
  VUE_APP_FIREBASE_PROJECT_ID = "poetic-torch-310010"
  VUE_APP_STORAGE_BUCKET = "poetic-torch-310010.appspot.com"
  VUE_APP_FIREBASE_MESSAGING_SENDER_ID = "477025938436"
  VUE_APP_FIREBASE_APP_ID = "1:477025938436:web:31e7a1806b3a3d94409951"
  VUE_APP_FIREBASE_MEASUREMENT_ID = "G-NLR588YGH3"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
